name: esdnet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - numpy=1.21.5
  - python=3.8.13
  - pytorch=1.10.1
  - pyyaml=6.0
  - tensorboardx=2.2
  - torchaudio=0.10.1
  - torchvision=0.11.2
  - tqdm=4.63.0
  - pip
  - pip:
    - gdown==4.5.1
    - lpips==0.1.4
    - opencv-python==4.5.5.64
    - scikit-image==0.19.2
    - thop==0.0.31-2005241907

